
name: Build RustDesk APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-20.04  # Используем старую версию Ubuntu
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Используем старую версию checkout
      with:
        submodules: false

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Flutter
      run: |
        # Устанавливаем конкретную версию Flutter вручную
        wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.16.9-stable.tar.xz
        tar xf flutter_linux_3.16.9-stable.tar.xz
        echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

    - name: Verify Flutter
      run: flutter --version

    - name: Install dependencies
      run: |
        cd flutter
        flutter pub get

    - name: Build APK
      run: |
        cd flutter
        flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: rustdesk-apk
        path: flutter/build/app/outputs/apk/release/app-release.apk
