
name: Build RustDesk APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.5'

    - name: Install dependencies
      run: |
        cd flutter
        flutter pub get

    - name: Build APK with Flutter
      run: |
        cd flutter
        flutter build apk --release
        ls -la build/app/outputs/apk/release/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-apk
        path: flutter/build/app/outputs/apk/release/app-release.apk
