
name: Build Stealth RustDesk

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      
    - name: Build Stealth APK
      run: |
        cd flutter
        flutter pub get
        flutter build apk --release --dart-define=STEALTH_MODE=true
        
    - name: Upload Stealth APK
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-stealth
        path: flutter/build/app/outputs/apk/release/app-release.apk
